#!/usr/bin/env node

let fs = require("fs");
let Phrase = require("jtellis-palindrome");
let text = fs.readFileSync("phrases.txt", "utf-8");


text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    fs.appendFileSync("palindrome.txt", `palindrome detected: ${line}\n`);
  }
});